### ISSUE TITLE
Breaks with Lita 4.6?

### ISSUE THREAD

**Issue by esigler** [jimmycuadra/lita-confirmation#5]
Howdy!

While chasing down an issue involving an internal plugin that uses lita-confirmation, we noticed that the plugin worked fine with lita 4.5, but breaks with 4.6.  Investigating further, it seems that the RSpec tests themselves for lita-confirmation break with lita 4.6.

Chasing that, it seems like the changes around the new Test Adapter might be the cause, but I haven't isolated it yet.

**Comment by jimmycuadra** [comment]
Thanks for the report. I'll look into it tonight!

**Comment by jimmycuadra** [comment]
Just released lita 4.6.1 which fixes this. Thanks again and sorry for the regression.
