### ISSUE TITLE
How to use confirmation to existing handler routes

### ISSUE THREAD

**Issue by akhy** [jimmycuadra/lita-confirmation#8]
From what I can see, the example in README only covers usage for handlers that we create ourselves (CMIIW).

Let's say I already have my Lita instance with a plugin to interact with Jenkins (via `gem install lita-jenkins`). What is the best way to attach the confirmation to the existing handler routes?

Thanks

**Comment by jimmycuadra** [comment]
The only way to do this today is by forking the plugin and updating the code. The next version of Lita will hopefully allow the ability to override pieces of third-party plugins directly from your configuration file.

**Comment by akhy** [comment]
Thanks.

Just found a hacky workaround by enumerating all Lita routes and injecting the extensions. I'm still new to Ruby, so it might not be idiomatic way.

``` ruby
Lita.handlers.each do |handler|
  next unless defined? handler.routes
  handler.routes.each do |route|
    if route.pattern === "jenkins build something"
      route.extensions[:confirmation] = {
        :restrict_to => :admin,
        :allow_self => false,
        :expire_after => 7200
      }
    end
  end
end
```

Here, "jenkins build something" is a sample message to find desired routes, since they can only identified by regex pattern.
